customhost = "employee.cufmwlul1bgh.ap-south-1.rds.amazonaws.com"
customuser = "admin"
custompass = "admin123"
customdb = "employee"
custombucket = "addemployeeminiproject"
customregion = "ap-south-1"
